# Generated by Django 3.0 on 2020-10-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enroll',
        ),
    ]
