# Generated by Django 3.0 on 2020-10-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_auto_20201022_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=5)),
                ('college', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
