# Generated by Django 3.0 on 2020-10-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='aplied',
        ),
        migrations.AddField(
            model_name='records',
            name='apbid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='dateisre',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='issued',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='stdenroll',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
