# Generated by Django 3.0 on 2020-10-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0012_auto_20201026_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brecord',
            name='idate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='brecord',
            name='rdate',
            field=models.DateField(null=True),
        ),
    ]
