# Generated by Django 3.0 on 2020-10-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0013_auto_20201026_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brecord',
            old_name='idate',
            new_name='issuedate',
        ),
        migrations.RenameField(
            model_name='brecord',
            old_name='rdate',
            new_name='returndate',
        ),
    ]
