# Generated by Django 3.0 on 2020-10-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0014_auto_20201026_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brecord',
            name='apbid',
            field=models.IntegerField(),
        ),
    ]
