# Generated by Django 3.0 on 2020-11-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0015_auto_20201026_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
