# Generated by Django 3.0 on 2020-01-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200109_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='usr',
            new_name='user',
        ),
    ]
