# Generated by Django 3.0 on 2020-11-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
