# Generated by Django 3.0 on 2020-11-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_module_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
    ]
