# Generated by Django 3.0 on 2020-10-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_remove_student_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enroll',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
