# Generated by Django 3.0 on 2020-10-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_auto_20201020_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='genres',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
