# Generated by Django 3.0 on 2020-10-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_books_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bimage',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
