# Generated by Django 3.0 on 2020-10-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0010_auto_20201026_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdenroll', models.CharField(max_length=15)),
                ('apbid', models.IntegerField(max_length=5)),
                ('issued', models.IntegerField(max_length=5)),
                ('idate', models.DateField()),
                ('rdate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Records',
        ),
    ]
