# Generated by Django 3.0 on 2020-10-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0011_auto_20201026_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brecord',
            name='issued',
            field=models.BooleanField(null=True),
        ),
    ]
